spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tailor_management
    username: root
    password: oz0oIa9EqUVt83l

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false